/* eslint-disable */
/**
 * @purpose Generated type-safe Tauri command bindings.
 * @role    Frontend command client generated from Rust DTOs and handlers.
 * @deps    @tauri-apps/api/core
 * @gotcha  Do not edit by hand; regenerate from src-tauri specta export.
 */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core'

/** Commands */
export const commands = {
  addProjectFromFolderPicker: () =>
    typedError<
      {
        id: string
        name: string
        rootPath: string
        workspaceRoot: string
        defaultBranch: string
        configSource: ConfigSourceDto
        archivePolicy: ArchivePolicyDto
      } | null,
      AppErrorDto
    >(__TAURI_INVOKE('add_project_from_folder_picker')),
  hidePanel: () => __TAURI_INVOKE<void>('hide_panel'),
  quitApp: () => __TAURI_INVOKE<void>('quit_app'),
  getLatestOperation: (input: OperationTargetInput) =>
    typedError<
      {
        id: string
        projectId: string
        workspaceId: string | null
        kind: OperationKindDto
        status: OperationStatusDto
        startedAt: string
        finishedAt: string | null
        exitCode: number | null
        logPath: string | null
        errorMessage: string | null
      } | null,
      AppErrorDto
    >(__TAURI_INVOKE('get_latest_operation', { input })),
  readOperationLog: (input: ReadOperationLogInput) =>
    typedError<OperationLogDto, AppErrorDto>(__TAURI_INVOKE('read_operation_log', { input })),
  createProject: (input: CreateProjectInput) =>
    typedError<ProjectDto, AppErrorDto>(__TAURI_INVOKE('create_project', { input })),
  importConductorProjects: (input: ImportConductorProjectsInput) =>
    typedError<ConductorImportCandidateDto[], AppErrorDto>(
      __TAURI_INVOKE('import_conductor_projects', { input })
    ),
  listProjects: () => typedError<ProjectDto[], AppErrorDto>(__TAURI_INVOKE('list_projects')),
  listWorktreeProjects: () =>
    typedError<WorktreeProjectDto[], AppErrorDto>(__TAURI_INVOKE('list_worktree_projects')),
  removeProject: (input: RemoveProjectInput) =>
    typedError<null, AppErrorDto>(__TAURI_INVOKE('remove_project', { input })),
  updateProjectSettings: (input: UpdateProjectSettingsInput) =>
    typedError<ProjectDto, AppErrorDto>(__TAURI_INVOKE('update_project_settings', { input })),
  getAppSettings: () => typedError<AppSettingsDto, AppErrorDto>(__TAURI_INVOKE('get_app_settings')),
  updateAppSettings: (input: UpdateAppSettingsInput) =>
    typedError<AppSettingsDto, AppErrorDto>(__TAURI_INVOKE('update_app_settings', { input })),
  archiveWorkspace: (input: ArchiveWorkspaceInput) =>
    typedError<WorkspaceDto, AppErrorDto>(__TAURI_INVOKE('archive_workspace', { input })),
  createWorkspace: (input: CreateWorkspaceInput) =>
    typedError<WorkspaceDto, AppErrorDto>(__TAURI_INVOKE('create_workspace', { input })),
  openWorkspace: (input: OpenWorkspaceInput) =>
    typedError<WorkspaceDto, AppErrorDto>(__TAURI_INVOKE('open_workspace', { input })),
  refreshProject: (input: RefreshProjectInput) =>
    typedError<WorkspaceDto[], AppErrorDto>(__TAURI_INVOKE('refresh_project', { input })),
  retryWorkspaceOperation: (input: RetryWorkspaceOperationInput) =>
    typedError<WorkspaceDto, AppErrorDto>(__TAURI_INVOKE('retry_workspace_operation', { input }))
}

/* Types */
export type AppErrorDto = {
  code: string
  message: string
  details: string | null
  recoverable: boolean
}

export type AppLanguageDto = 'system' | 'zh_cn' | 'en_us'

export type AppSettingsDto = {
  language: AppLanguageDto
  hoverQuickOpenTargets: OpenWorkspaceTargetDto[]
  defaultArchivePolicy: ArchivePolicyDto
  removeProjectBehavior: RemoveProjectBehaviorDto
  newProjectPosition: NewProjectPositionDto
}

export type ArchivePolicyChoiceDto = 'hide' | 'remove_worktree'

export type ArchivePolicyDto = 'use_global' | 'ask' | 'hide' | 'remove_worktree'

export type ArchiveWorkspaceInput = {
  workspaceId: string
  policy: ArchivePolicyChoiceDto | null
  rememberPolicy: boolean
}

export type ConductorImportCandidateDto = {
  repoName: string
  rootPath: string
  workspaceRoot: string
  configSource: ConfigSourceDto
  workspaces: WorkspaceDto[]
  warnings: string[]
}

export type ConfigSourceDto = 'conductor_settings' | 'conductor_json' | 'grove_override' | 'none'

export type CreateProjectInput = {
  rootPath: string
}

export type CreateWorkspaceInput = {
  projectId: string
  name: string
  branch: string
  baseBranch: string
  runSetup: boolean
}

export type ImportConductorProjectsInput = {
  workspaceRoot: string | null
}

export type NewProjectPositionDto = 'first' | 'last'

export type OpenWorkspaceInput = {
  workspaceId: string
  target: OpenWorkspaceTargetDto
}

export type OpenWorkspaceTargetDto =
  | 'finder'
  | 'zed'
  | 'cursor'
  | 'vs_code'
  | 'ghostty'
  | 'terminal'

export type OperationDto = {
  id: string
  projectId: string
  workspaceId: string | null
  kind: OperationKindDto
  status: OperationStatusDto
  startedAt: string
  finishedAt: string | null
  exitCode: number | null
  logPath: string | null
  errorMessage: string | null
}

export type OperationKindDto =
  | 'import'
  | 'refresh'
  | 'create'
  | 'setup'
  | 'archive'
  | 'remove_project'
  | 'open_editor'
  | 'open_terminal'
  | 'reveal_finder'

export type OperationLogDto = {
  operationId: string
  content: string
}

export type OperationStatusDto = 'queued' | 'running' | 'succeeded' | 'failed'

export type OperationTargetInput = {
  projectId: string | null
  workspaceId: string | null
}

export type ProjectCommandsDto = {
  setup: string
  archive: string
}

export type ProjectDto = {
  id: string
  name: string
  rootPath: string
  workspaceRoot: string
  defaultBranch: string
  configSource: ConfigSourceDto
  archivePolicy: ArchivePolicyDto
}

export type ReadOperationLogInput = {
  operationId: string
}

export type RefreshProjectInput = {
  projectId: string
}

export type RemoveProjectBehaviorDto = 'grove_only' | 'delete_worktrees'

export type RemoveProjectInput = {
  projectId: string
}

export type RetryWorkspaceOperationInput = {
  workspaceId: string
}

export type UpdateAppSettingsInput = {
  language: AppLanguageDto
  hoverQuickOpenTargets: OpenWorkspaceTargetDto[]
  defaultArchivePolicy: ArchivePolicyDto
  removeProjectBehavior: RemoveProjectBehaviorDto
  newProjectPosition: NewProjectPositionDto
}

export type UpdateProjectSettingsInput = {
  projectId: string
  workspaceRoot: string
  archivePolicy: ArchivePolicyDto
  commands: ProjectCommandsDto
}

export type WorkspaceDto = {
  id: string
  projectId: string
  name: string
  branch: string
  baseBranch: string | null
  path: string
  lifecycleStatus: WorkspaceLifecycleStatusDto
  operationStatus: WorkspaceOperationStatusDto
  hiddenAt: string | null
  staleAt: string | null
  gitState: WorkspaceGitStateDto | null
}

export type WorkspaceGitStateDto = {
  ahead: number
  behind: number
  dirty: number
  lastCommitMessage: string
  capturedAt: string
}

export type WorkspaceLifecycleStatusDto = 'active' | 'hidden' | 'stale'

export type WorkspaceOperationStatusDto =
  | 'idle'
  | 'creating'
  | 'setting_up'
  | 'archiving'
  | 'failed'

export type WorktreeProjectDto = {
  project: ProjectDto
  commands: ProjectCommandsDto
  workspaces: WorkspaceDto[]
}

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
  try {
    return { status: 'ok', data: await result }
  } catch (e) {
    if (e instanceof Error) throw e
    return { status: 'error', error: e as any }
  }
}
