/* eslint-disable */
/**
 * @purpose Generated type-safe Tauri command bindings.
 * @role    Frontend command client generated from Rust DTOs and handlers.
 * @deps    @tauri-apps/api/core
 * @gotcha  Do not edit by hand; regenerate from src-tauri specta export.
 */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core'

/** Commands */
export const commands = {
  hidePanel: () => __TAURI_INVOKE<void>('hide_panel'),
  quitApp: () => __TAURI_INVOKE<void>('quit_app'),
  importConductorProjects: (input: ImportConductorProjectsInput) =>
    typedError<ConductorImportCandidateDto[], AppErrorDto>(
      __TAURI_INVOKE('import_conductor_projects', { input })
    ),
  listProjects: () => typedError<ProjectDto[], AppErrorDto>(__TAURI_INVOKE('list_projects')),
  listWorktreeProjects: () =>
    typedError<WorktreeProjectDto[], AppErrorDto>(__TAURI_INVOKE('list_worktree_projects')),
  updateProjectSettings: (input: UpdateProjectSettingsInput) =>
    typedError<ProjectDto, AppErrorDto>(__TAURI_INVOKE('update_project_settings', { input })),
  archiveWorkspace: (input: ArchiveWorkspaceInput) =>
    typedError<WorkspaceDto, AppErrorDto>(__TAURI_INVOKE('archive_workspace', { input })),
  createWorkspace: (input: CreateWorkspaceInput) =>
    typedError<WorkspaceDto, AppErrorDto>(__TAURI_INVOKE('create_workspace', { input })),
  openWorkspace: (input: OpenWorkspaceInput) =>
    typedError<WorkspaceDto, AppErrorDto>(__TAURI_INVOKE('open_workspace', { input })),
  refreshProject: (input: RefreshProjectInput) =>
    typedError<WorkspaceDto[], AppErrorDto>(__TAURI_INVOKE('refresh_project', { input }))
}

/* Types */
export type AppErrorDto = {
  code: string
  message: string
  details: string | null
  recoverable: boolean
}

export type ArchivePolicyChoiceDto = 'hide' | 'remove_worktree'

export type ArchivePolicyDto = 'ask' | 'hide' | 'remove_worktree'

export type ArchiveWorkspaceInput = {
  workspaceId: string
  policy: ArchivePolicyChoiceDto
  rememberPolicy: boolean
}

export type ConductorImportCandidateDto = {
  repoName: string
  rootPath: string
  workspaceRoot: string
  configSource: ConfigSourceDto
  workspaces: WorkspaceDto[]
  warnings: string[]
}

export type ConfigSourceDto = 'conductor_settings' | 'conductor_json' | 'grove_override' | 'none'

export type CreateWorkspaceInput = {
  projectId: string
  name: string
  branch: string
  baseBranch: string
  runSetup: boolean
}

export type ImportConductorProjectsInput = {
  workspaceRoot: string | null
}

export type OpenWorkspaceInput = {
  workspaceId: string
  target: OpenWorkspaceTargetDto
}

export type OpenWorkspaceTargetDto =
  | 'finder'
  | 'zed'
  | 'cursor'
  | 'vs_code'
  | 'ghostty'
  | 'terminal'

export type ProjectCommandsDto = {
  run: string
  setup: string
  archive: string
}

export type ProjectDto = {
  id: string
  name: string
  rootPath: string
  workspaceRoot: string
  defaultBranch: string
  configSource: ConfigSourceDto
  archivePolicy: ArchivePolicyDto
}

export type RefreshProjectInput = {
  projectId: string
}

export type UpdateProjectSettingsInput = {
  projectId: string
  workspaceRoot: string
  archivePolicy: ArchivePolicyDto
  commands: ProjectCommandsDto
}

export type WorkspaceDto = {
  id: string
  projectId: string
  name: string
  branch: string
  baseBranch: string | null
  path: string
  lifecycleStatus: WorkspaceLifecycleStatusDto
  operationStatus: WorkspaceOperationStatusDto
  hiddenAt: string | null
  staleAt: string | null
  gitState: WorkspaceGitStateDto | null
}

export type WorkspaceGitStateDto = {
  ahead: number
  behind: number
  dirty: number
  lastCommitMessage: string
  capturedAt: string
}

export type WorkspaceLifecycleStatusDto = 'active' | 'hidden' | 'stale'

export type WorkspaceOperationStatusDto =
  | 'idle'
  | 'creating'
  | 'setting_up'
  | 'archiving'
  | 'failed'

export type WorktreeProjectDto = {
  project: ProjectDto
  commands: ProjectCommandsDto
  workspaces: WorkspaceDto[]
}

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
  try {
    return { status: 'ok', data: await result }
  } catch (e) {
    if (e instanceof Error) throw e
    return { status: 'error', error: e as any }
  }
}
